Hyperlink check errors with space in file name
When running the test:links script the following error may be caused by a file with a space in its name.

```bash
ERROR: File not found! Please provide a valid filename as an argument.
```